### PR TITLE
Enums, IRC connection fix

### PR DESCRIPTION
**Pull request by Codingale**
Making Enums for Easier readablity.

### CODE REVIEW

**Comment by Codingale** [comment]
Tested changes as well as I can. No conflicts with existing code.

**Comment by hodlhodl1132** [comment]
Unable to purchase items when merging with master

**Comment by Codingale** [comment]
Odd at the time I was able to, did you change how the products types are saved (IE. no longer ints) and did you reset product prices as I've had a long standing bug with that. Will check later today.

**Comment by hodlhodl1132** [comment]
I haven't changed how product how product types are saved, they are still ints. Product prices should be set when opening mod for first time now.

**Comment by Codingale** [comment]
I'm unable to reproduce that. I even changed the price of a few items and restarted and it seems to work.

**Comment by hodlhodl1132** [comment]
I was using the wrong command or I merged it wrong

**Pull request merged**
